{joy_node_name}:
  ros__parameters:
    device_id: {device_id}
    deadzone: 0.05
    autorepeat_rate: 20.0
    use_sim_time: false

{teleop_node_name}:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    enable_button: 1
    enable_turbo_button: 3

    require_enable_button: true
    use_sim_time: false
