joy_node1:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

joy_node2:
  ros__parameters:
    device_id: 1
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node1:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0


    enable_button: 1
    enable_turbo_button: 3

    require_enable_button: true

teleop_node2:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0


    enable_button: 8
    enable_turbo_button: 9

    require_enable_button: true